"""initial

Revision ID: 790d986667dc
Revises: 
Create Date: 2026-04-29 13:52:55.204276

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '790d986667dc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alert', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_alert_user_id', 'user', ['user_id'], ['id'])

    with op.batch_alter_table('climate_profiles', schema=None) as batch_op:
        batch_op.drop_column('planting_window_end')
        batch_op.drop_column('drought_risk')
        batch_op.drop_column('heatwave_risk')
        batch_op.drop_column('flood_risk')
        batch_op.drop_column('planting_window_start')

    with op.batch_alter_table('crop', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('current_growth_stage', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('current_health_status', sa.String(length=50), nullable=True))
        batch_op.create_foreign_key('fk_crop_user_id', 'user', ['user_id'], ['id'])
        batch_op.drop_column('water_requirement')
        batch_op.drop_column('health_status')
        batch_op.drop_column('growth_stage')

    with op.batch_alter_table('field', schema=None) as batch_op:
        batch_op.drop_column('disease_risk')
        batch_op.drop_column('growth_stage')

    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_column('assigned_to')
        batch_op.drop_column('pesticide_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pesticide_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('assigned_to', sa.VARCHAR(length=100), nullable=True))
        batch_op.create_foreign_key('fk_task_pesticide_id', 'pesticide_use', ['pesticide_id'], ['pesticide_id'])

    with op.batch_alter_table('field', schema=None) as batch_op:
        batch_op.add_column(sa.Column('growth_stage', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('disease_risk', sa.VARCHAR(length=100), nullable=True))

    with op.batch_alter_table('crop', schema=None) as batch_op:
        batch_op.add_column(sa.Column('growth_stage', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('health_status', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('water_requirement', sa.FLOAT(), nullable=True))
        batch_op.drop_constraint('fk_crop_user_id', type_='foreignkey')
        batch_op.drop_column('current_health_status')
        batch_op.drop_column('current_growth_stage')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('climate_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('planting_window_start', sa.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('flood_risk', sa.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('heatwave_risk', sa.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('drought_risk', sa.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('planting_window_end', sa.VARCHAR(length=20), nullable=True))

    with op.batch_alter_table('alert', schema=None) as batch_op:
        batch_op.drop_constraint('fk_alert_user_id', type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
