""" Keeps record of alerts generated by the system, 
such as weather change, daily task change, or weekly plan change. 
Also alerts about critical crop health, critical field actions, critical tasks, and critical weather conditions. """

from app.extensions import db

class Alert(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer, db.ForeignKey("user.id"), nullable=False)
    message = db.Column(db.String(200))
    level = db.Column(db.String(20))  # Critical, high, medium, low
    crop_id = db.Column(db.Integer)